### ISSUE TITLE
Expected behavior from failed transactions

### ISSUE THREAD

**Issue by samolition** [LN-Zap/zap-desktop#3718]
This is less a bug than a request for what the expected behavior should be for a failed transaction. Background, I initiated a transaction from zap-desktop 0.7.2 beta on Windows (20H2) 1/9/21, I did so with a low fee using the predetermined rates in the client. The transaction went through at 1 sat per byte, and has been stuck since. 

Transaction was sent from Zap-desktop to Coinbase wallet. I have connected to the LND instance created by the Zap install (which is no longer allowing me to connect over 11009, it uses dynamics), and tried using the "lncli wallet bumpfee" command, but the command will not go through successfully (index does not belong to wallet). 

If/when the transaction fails, will my funds be returned to my wallet? Are there any steps I can take to get the transaction through successfully?

**Comment by bolatovumar** [comment]
I believe the transaction will be dropped from the mempool eventually (if it hasn't been already). You won't lose access to the funds. In the meantime you could try compiling LND from source and recovering the funds that way but it does require some effort.

**Comment by samolition** [comment]
@bolatovumar Understood. The transaction details still pull on blockchair, though it doesn't show up on other explorers. Once it's not pulling from any explorers, the balance should come back to my wallet (currently balance isn't in my wallet and transaction just shows as pending)?

**Comment by bolatovumar** [comment]
> @bolatovumar Understood. The transaction details still pull on blockchair, though it doesn't show up on other explorers. Once it's not pulling from any explorers, the balance should come back to my wallet (currently balance isn't in my wallet and transaction just shows as pending)?

I'm not sure what the behavior would be in this case but you will definitely not lose funds.

**Comment by samolition** [comment]
So the transaction fell off mempool a few days ago, I waited a few extra days to be safe and verify it wouldn't pop back up. I opened Zap moments ago, and it just rebroadcast the transaction and its back in the mempool. How can I prevent it from doing this and retrieve my funds?

**Comment by bolatovumar** [comment]
> So the transaction fell off mempool a few days ago, I waited a few extra days to be safe and verify it wouldn't pop back up. I opened Zap moments ago, and it just rebroadcast the transaction and its back in the mempool. How can I prevent it from doing this and retrieve my funds?

You can wait for it for leave the mempool and using LND which you build from source code to rebroadcast the transaction.

**Comment by grubeli** [comment]
DONE.
Okay. I found a way to return our funds.
if your funds are stuck like mine, I mean you send them from Zap (on-chain) wallet to Zap Lightening and is stuck on Pending.
What you need is to copy your recovery words, download new app on a different PC and recover (!) your wallet from the seed numbers you copied before. if you don't have a different PC you can use virtualization software like virtualbox (https://www.virtualbox.org) to create a virtual PC and install Zap on it.

After that, when you open your Zap on that new PC you will see all your coins on On-Chain, it means you can send it back to your original account/address or any other address

**Comment by samolition** [comment]
@grubeli Thank you, that was what I needed. TX had been stuck since 1/9, couldn't get that info out of anyone here/slack/reddit. Tried it last night despite the TX still showing up on the chain and the funds came back, immediately sent them to another wallet.
